=== randyvp/oink_magento/lib/VirtualPiggy/Schemas/virtualpiggy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cart">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cart-shipment">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="shipment-tax">
                <xs:complexType>
                  <xs:attribute name="total" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="shipment-cost" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="total" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="shipment-discount" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:attribute name="total" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="reward-points" minOccurs="0" maxOccurs="1" >
                <xs:complexType>
                  <xs:attribute name="total" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="shipment-address" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="address" />
                    <xs:element name="zip" />
                    <xs:element name="city" />
                    <xs:element name="state" />
                    <xs:element name="country" minOccurs="0" maxOccurs="1" />
                    <xs:element name="phone"  minOccurs="0" maxOccurs="1" />
                    <xs:element name="name" minOccurs="0" maxOccurs="1" />
                    <xs:element name="attention-of" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="items">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="item">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="item-identifier" type="xs:string" minOccurs="0" />
                          <xs:element name="item-name" type="xs:string" />
                          <xs:element name="item-description" type="xs:string" />
                          <xs:element name="item-price" type="xs:decimal" />
                          <xs:element name="item-quantity" type="xs:int" />
                        </xs:sequence>
                        <xs:attribute name="total" type="xs:decimal" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="total" type="xs:decimal" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="currency" type="xs:string" use="optional" default="USD" />
      <xs:attribute name="total" type="xs:decimal" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== randyvp/oink_magento/lib/VirtualPiggy/Schemas/cart_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns1:cart
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='null'
    xsi:schemaLocation='null VirtualPiggy.xsd'>
    <ns1:cart-shipment total="5.00">
        <ns1:shipment-tax total="0.00"></ns1:shipment-tax>
        <ns1:shipment-cost total="0.00"></ns1:shipment-cost>
        <ns1:shipment-discount total="0.00"></ns1:shipment-discount>
        <ns1:reward-points total="0"></ns1:reward-points>
        <ns1:shipment-address>
            <ns1:address>1234 easy st</ns1:address>
            <ns1:zip>91367</ns1:zip>
            <ns1:city>woodland</ns1:city>
            <ns1:state>ca</ns1:state>
            <ns1:country>US</ns1:country>
            <ns1:phone>555.555.5555</ns1:phone>
            <ns1:name>parent</ns1:name>
            <ns1:attention-of>kid</ns1:attention-of>
        </ns1:shipment-address>
        <ns1:items>
            <ns1:item total="5.00">
                <ns1:item-identifier>toy01</ns1:item-identifier>
                <ns1:item-name>fun toy</ns1:item-name>
                <ns1:item-description>a really cool toy</ns1:item-description>
                <ns1:item-price>5.00</ns1:item-price>
                <ns1:item-quantity>1</ns1:item-quantity>
            </ns1:item>
        </ns1:items>
    </ns1:cart-shipment>

</ns1:cart>

=== randyvp/oink_magento/lib/VirtualPiggy/Schemas/cart.xml
<?xml version="1.0" encoding="UTF-8"?>
<vp:cart
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:vp='null'
    xsi:schemaLocation='null https://development.virtualpiggy.com/Schemas/VirtualPiggy.xsd'>
    <vp:cart-shipment total="5.00">
        <vp:shipment-tax total="0.00"></vp:shipment-tax>
        <vp:items>
            <vp:item total="5.00">
                <vp:item-name>Buzz lightyear</vp:item-name>
                <vp:item-description>Toystory toy</vp:item-description>
                <vp:item-price>5.00</vp:item-price>
                <vp:item-quantity>1</vp:item-quantity>
            </vp:item>
        </vp:items>
    </vp:cart-shipment>
</vp:cart>
